# This file contains the parameters of the EC-thor node

# General parameters
common:
  topics:
    input:
      point_cloud: "/limovelo/full_pcl"        # Point cloud input topic
      odom: "/limovelo/state"                  # Odometry input topic
    output:
      observations: "/AS/P/ecthor/observations"          # Output topic for observations
      state: "/AS/P/ecthor/state"                        # Output topic for state vehicle
      walls: "/AS/P/ecthor/debug/walls"                        # Output topic for walls
      ground: "/AS/P/ecthor/debug/ground"                # Output topic for ground (debug)
      obstacles: "/AS/P/ecthor/debug/obstacle"           # Output topic for obstacle (debug)
      buffer: "/AS/P/ecthor/debug/buffer"                # Output topic for buffer (debug)
      clusters: "/AS/P/ecthor/debug/clusters"            # Output topic for points clusters (debug)
      centroides: "/AS/P/ecthor/debug/centroides"        # Output topic for centroides clusters (debug)


# Manager parameters
manager:
  publish_debug: false                        # True: Publish debug topics/ False: Do not publish debug topics
  reconstruct: false                          # True: Recontruction cluster through an ikdTree

# Processor parameters  
processor:
  remove_walls: true                         # True: Remove walls/ False: Do not remove walls
  init_iterations: 10                        # Number of iterations to initialize the processor
  waggner:
    grid_size: 200                           # grid size
    cell_size: 1.0                           # cell size
    min_height: 1.0                          # min height for wall
    max_iterations: 1000                     # max iterations
    distance_threshold: 0.1                 # distance threshold
    max_slope: 0.2                           # max slope
    max_error: 0.1                           # max error
    max_z:  1.0                              # max z
    min_z: -1.0                              # min z
    max_range: 50.0                          # max range

# Accumulator parameters
accumulator:
  buffer_size: 50000                           # max size of the buffer
  filter: true                                 # True: Filter the buffer/ False: Do not filter the buffer
  radius: 50                                   # Filter radius
  field_of_view: 160                           # Filter field of view [-fov/2,fov/2] (degrees)
  threads: 4                                   # Number of threads for the accumulator 


# Detector parameters
detect:
  hiperparams:
    eps: 0.25                                # search radius 
    maxPts: 1000                              # maxim points of a cluster
    minPts: 4                                # minim points of a cluster

# Reconstructor parameters
reconstr:
  delete_param: 0.3 
  balance_param: 0.6
  box_length: 0.005
  downsample: true                          # Downsampling highly recommended
  mode: false                                # True: K Nearest Search / False: Radial search
  k_nearest: 128                            # number of nearest neighbors to search for
  max_dist: 1.0                             # max distance to search for nearest neighbors
  radius: 0.35                               # radius of the search
